### ISSUE TITLE
twemoji SVGs contains no gradients

### ISSUE THREAD

**Issue by anthrotype** [rsheeter/color-fonts#1]
If I grep for `linearGradient` or `radialGradient` inside `font-srcs/twemoji/assets/svg` directory, I get 0 results. So it appears that Twemoji svgs are all flat colors, without gradients.

Also, the test font as generated by `update-samples.sh` script containing Twemoji's smileyes ends up being built as a COLRv0 font, even if nanoemoji script is called with `--color_format corl_1`, this is because none of the color layers for the selected emojis contain any opacity/transparency.
When a color glyph only uses opaque colors without any gradients, the fonttools colorLib builder automatically encodes it in the COLRv0 portion of COLR table (as it is more compact than the v1 equivalent).

https://github.com/fonttools/fonttools/pull/1822/files#diff-9daa4995838963ff3909314f68952cbfR277-R299

The `colorLib.buildCOLR` method has an option to set the version explicitly (instead of automatically based on content) but it is not exposed to ufo2ft yet.

I am not sure whether all Twemoji svgs have flat and solid colors with no transparency. But if that is the case, then using Twemoji for testing COLRv1 implementation does not make much sense.

**Comment by rsheeter** [comment]
It isn't my intent for this repo to exclusively have COLRv1 samples. I think I will likely update the twemoji one to COLRv0.

**Comment by rsheeter** [comment]
For context, as the tools mature and we start to implement optimizations like shape reuse and the like I aspire to provide samples of COLR vs X vs Y so we can see the filesize implications and potentially even test other things like cost to parse/render.
